name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master,main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, main ]
#Specify all jobs here::
jobs:
#Build of first job::
  build:
    runs-on: ubuntu-latest
#Steps involved in first job::
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
        
